name: buildbot

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check:
    name: Static analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - uses: android-actions/setup-android@v2
        name: Set up Android SDK

      - name: Check for dependency updates
        uses: gradle/gradle-command-action@v2
        with:
          arguments: app:staticAnalysis app:collectSarifReports --continue

  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - uses: android-actions/setup-android@v2
        name: Set up Android SDK

      - name: Run tests with Gradle
        uses: gradle/gradle-command-action@v2
        with:
          arguments: test --continue
