name: dependency updates

on:
  workflow_dispatch:
  schedule:
    # Every Thursday at 4:32 (note scheduled jobs might be delayed or skipped)
    - cron: '32 4 * * 4'

jobs:
  check:
    name: Check for updated dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - uses: android-actions/setup-android@v2
        name: Set up Android SDK

      - name: Check for dependency updates
        uses: gradle/gradle-command-action@v2
        with:
          arguments: versionCatalogUpdate

      # Prevent the change to gradlew to be included in the PR
      - name: Revert gradlew change
        run: git checkout gradlew

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Dependency updates
          delete-branch: true
          branch: catalog-dependency-updates
          title: Dependency updates
          body: Here are some suggested updates to dependencies :)
